version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=synchrenity
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: synchrenity
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
