

name: Synchrenity CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 2 * * 1-5"
jobs:
  build:
    name: Build & Test (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          tools: composer:v2, php-cs-fixer, phpstan
      # Debug line removed
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Clear composer cache
        run: composer clear-cache
      - name: Install dependencies
        run: composer install
      - name: Install php-cs-fixer and phpstan if missing
        run: |
          if [ ! -f vendor/bin/php-cs-fixer ]; then composer require --dev friendsofphp/php-cs-fixer; fi
          if [ ! -f vendor/bin/phpstan ]; then composer require --dev phpstan/phpstan; fi
      - name: Run code style checks (php-cs-fixer)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Run static analysis (phpstan)
        run: vendor/bin/phpstan analyse --no-progress
      - name: Run tests with coverage
        run: vendor/bin/phpunit --testdox --coverage-clover=coverage.xml || vendor/bin/phpunit --testdox

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            coverage.xml
            vendor/**
