name: Synchrenity CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Clear composer cache
        run: composer clear-cache
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run code style checks (php-cs-fixer)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
      - name: Run static analysis (phpstan)
        run: vendor/bin/phpstan analyse --no-progress
      - name: Run tests
        run: vendor/bin/phpunit --testdox tests